#!/usr/bin/env python3
"""Semi-automated onboarding for unknown bioinformatics programs.

The tool is intentionally conservative:

- ``probe`` and ``plan-install`` only write project-local evidence files.
- ``install`` executes only a proposal generated by this script and requires
  ``--yes``.
- Third-version automatic installation supports Conda/Mamba environments only.
  Source, binary, GitHub, and container routes can be proposed but are not
  executed here.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

# Allow ``import menu`` when this script is launched from any working directory.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import menu  # noqa: E402  (sys.path tweak above is intentional)


REPO_ROOT = Path(__file__).resolve().parents[1]
CARD_DRAFT_DIR = REPO_ROOT / "references" / "program-cards" / "drafts"
PROTECTED_WRITE_ROOTS = (
    Path.home() / "data",
    Path.home() / "tools",
)
BROAD_PROJECT_ROOTS = (
    Path("/"),
    Path("/data9"),
    Path("/data9/home"),
    Path.home(),
    Path.home() / "projects",
)

SCHEMA_VERSION = "program_onboarding.v3"
CREATED_BY = "bio-workflow program_onboard.py"
DEFAULT_CHANNELS = ["conda-forge", "bioconda", "defaults"]
VERSION_FLAGS = ["--version", "version", "-v", "-version"]
HELP_FLAGS = ["--help", "-h", "help"]
OUTPUT_LIMIT = 120_000

SHELL_CONTROL_TOKENS = {";", "&&", "||", "|", ">", ">>", "<", "$(", "`"}


@dataclass(frozen=True)
class ChoiceOption:
    label: str
    value: str
    description: str
    path: str = ""
    needs_text: bool = False
    text_prompt: str = ""


@dataclass(frozen=True)
class ChoiceQuestion:
    key: str
    title: str
    options: tuple[ChoiceOption, ...]
    default_index: int = 0


def now_stamp() -> str:
    return datetime.now().astimezone().strftime("%Y%m%dT%H%M%S")


def iso_now() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def program_key(value: str) -> str:
    text = Path(value).name if "/" in value else value
    text = text.strip().lower().replace("_", "-")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-")
    return text or "program"


def safe_env_name(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z0-9_.-]+", name)) and not name.startswith("-") and "/" not in name


def is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def rel(path: Path) -> str:
    resolved = path.resolve()
    for base in (Path.cwd(), REPO_ROOT):
        try:
            return str(resolved.relative_to(base.resolve()))
        except ValueError:
            continue
    return str(resolved)


def resolve_under_project(path: Path | str, project_root: Path) -> Path:
    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = project_root / candidate
    return candidate.resolve()


def is_protected_write_path(path: Path) -> bool:
    resolved = path.resolve()
    if any(is_relative_to(resolved, root) for root in PROTECTED_WRITE_ROOTS):
        return True
    # Also protect any account's raw-data/tools on this cluster:
    # /data9/home/<user>/data[/...] and /data9/home/<user>/tools[/...].
    parts = resolved.parts
    return (
        len(parts) >= 5
        and parts[1] == "data9"
        and parts[2] == "home"
        and parts[4] in {"data", "tools"}
    )


def validate_project_root(path: str | None) -> Path:
    root = Path(path).expanduser() if path else Path.cwd()
    resolved = root.resolve()
    if resolved in {item.resolve() for item in BROAD_PROJECT_ROOTS}:
        raise ValueError(f"project root is too broad for onboarding writes: {resolved}")
    if is_protected_write_path(resolved):
        raise ValueError(f"project root must not be under protected data/tools roots: {resolved}")
    return resolved


def onboard_root(project_root: Path) -> Path:
    return project_root / "reports" / "program-onboarding"


def choice_root(project_root: Path) -> Path:
    return project_root / "config"


def choice_dir(project_root: Path) -> Path:
    return choice_root(project_root) / "program-onboarding"


def validate_project_path(
    path: Path,
    allowed_root: Path,
    label: str,
    allow_external: bool = False,
    external_hint: str = "--allow-external-paths",
) -> Path:
    resolved = path.expanduser().resolve()
    if is_protected_write_path(resolved):
        raise ValueError(f"{label} must not be under a protected data/tools directory (e.g. ~/data or ~/tools)")
    if allow_external:
        return resolved
    if not is_relative_to(resolved, allowed_root):
        raise ValueError(f"{label} must be under {rel(allowed_root)}; use {external_hint} only for non-install smoke tests")
    return resolved


def looks_like_onboarding_bundle(path: Path) -> bool:
    parts = path.resolve().parts
    return len(parts) >= 4 and parts[-4] == "reports" and parts[-3] == "program-onboarding" and bool(parts[-2]) and bool(parts[-1])


def validate_bundle_dir(bundle: Path, project_root: Path | None = None, allow_external: bool = False) -> Path:
    resolved = bundle.expanduser().resolve()
    if is_protected_write_path(resolved):
        raise ValueError("evidence dir must not be under a protected data/tools directory (e.g. ~/data or ~/tools)")
    if allow_external:
        return resolved
    if project_root is not None and not is_relative_to(resolved, project_root):
        raise ValueError(f"evidence dir must be under project root {rel(project_root)}")
    if not looks_like_onboarding_bundle(resolved):
        raise ValueError("evidence dir must follow <project>/reports/program-onboarding/<program_key>/<timestamp>")
    return resolved


def validated_out_root(out_root: str | None, project_root: Path, allow_external: bool = False) -> Path:
    root = resolve_under_project(out_root, project_root) if out_root else onboard_root(project_root)
    return validate_project_path(root, onboard_root(project_root), "out root", allow_external)


def validated_draft_path(path: Path, allow_external: bool = False) -> Path:
    return validate_project_path(path, CARD_DRAFT_DIR, "draft card path", allow_external)


def validated_choice_output_path(path: Path, project_root: Path, allow_external: bool = False) -> Path:
    return validate_project_path(
        resolve_under_project(path, project_root),
        choice_root(project_root),
        "choice output path",
        allow_external,
        "--allow-external-output",
    )


def unsafe_token(value: str, *, allow_slash: bool = False) -> bool:
    if not value or any(token in value for token in SHELL_CONTROL_TOKENS):
        return True
    if any(ch.isspace() for ch in value):
        return True
    if value.startswith("-"):
        return True
    if not allow_slash and ("/" in value or "\\" in value):
        return True
    return False


def truncate(text: str, limit: int = OUTPUT_LIMIT) -> str:
    if len(text) <= limit:
        return text
    omitted = len(text) - limit
    return text[:limit] + f"\n\n[truncated {omitted} characters]\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def ensure_bundle(key: str, out_root: Path) -> Path:
    base = out_root / key / now_stamp()
    bundle = base
    suffix = 2
    while bundle.exists():
        bundle = Path(f"{base}-{suffix}")
        suffix += 1
    bundle.mkdir(parents=True, exist_ok=False)
    return bundle


def write_intent(
    bundle: Path,
    program: str,
    key: str,
    action: str,
    status: str,
    extra: dict[str, str] | None = None,
) -> None:
    rows = [
        {"Field": "Program", "Value": program},
        {"Field": "Program_Key", "Value": key},
        {"Field": "Action", "Value": action},
        {"Field": "Status", "Value": status},
        {"Field": "Created_At", "Value": iso_now()},
    ]
    for field, value in (extra or {}).items():
        rows.append({"Field": field, "Value": value})
    write_tsv(bundle / "intent.tsv", rows, ["Field", "Value"])


def read_intent(bundle: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for row in read_tsv(bundle / "intent.tsv"):
        field = row.get("Field", "")
        if field:
            values[field] = row.get("Value", "")
    return values


def default_choice_output(program: str, project_root: Path) -> Path:
    return choice_dir(project_root) / f"{program_key(program)}_choice.json"


def source_default_index(default_source: str) -> int:
    order = ["conda", "github", "container", "binary", "custom"]
    try:
        return order.index(default_source)
    except ValueError:
        return 0


def onboarding_choice_questions(
    program: str,
    default_source: str = "conda",
    project_root: Path | None = None,
) -> tuple[ChoiceQuestion, ...]:
    key = program_key(program)
    project_root = project_root or Path.cwd().resolve()
    return (
        ChoiceQuestion(
            key="install_location",
            title=f"{program} install location",
            options=(
                ChoiceOption(
                    label="Project-local test install",
                    value="project_local",
                    description="Recommended for first contact; writes under this project and is easy to inspect.",
                    path=str(project_root / "tools" / key),
                ),
                ChoiceOption(
                    label="User tools long-term install",
                    value="user_tools",
                    description="Writes under ~/tools and requires explicit confirmation.",
                    path=str(Path.home() / "tools" / key),
                ),
                ChoiceOption(
                    label="Do not install yet",
                    value="no_install",
                    description="Keep discovery/proposal only; no clone, no env creation, no tool writes.",
                ),
                ChoiceOption(
                    label="Type something",
                    value="custom",
                    description="Enter a custom install directory.",
                    needs_text=True,
                    text_prompt="Install directory: ",
                ),
            ),
            default_index=0,
        ),
        ChoiceQuestion(
            key="source_type",
            title=f"{program} install source",
            options=(
                ChoiceOption(
                    label="Conda/Bioconda package",
                    value="conda",
                    description="Executable after confirmation; prefer only when no suitable official container route exists.",
                ),
                ChoiceOption(
                    label="GitHub/source repo",
                    value="github",
                    description="Proposal-only in program_onboard.py; manual review before clone/build.",
                ),
                ChoiceOption(
                    label="Container image",
                    value="container",
                    description="Prefer for official Docker/Singularity/Apptainer images; proposal-only before pull/run.",
                ),
                ChoiceOption(
                    label="Binary/manual source",
                    value="binary",
                    description="Proposal-only; requires checksum/source/path review.",
                ),
                ChoiceOption(
                    label="Type something",
                    value="custom",
                    description="Describe a different source or package route.",
                    needs_text=True,
                    text_prompt="Source/package route: ",
                ),
            ),
            default_index=source_default_index(default_source),
        ),
        ChoiceQuestion(
            key="pilot_input",
            title=f"{program} minimal pilot input",
            options=(
                ChoiceOption(
                    label="I provide paths",
                    value="explicit_paths",
                    description="Use exact input files or a manifest; no broad discovery.",
                    needs_text=True,
                    text_prompt="Input path(s) or manifest, comma-separated if needed: ",
                ),
                ChoiceOption(
                    label="Bounded directory search",
                    value="bounded_search",
                    description="Search only a named root with maxdepth and pattern.",
                    needs_text=True,
                    text_prompt="Root/maxdepth/pattern, for example /path maxdepth=2 pattern='*.fq.gz': ",
                ),
                ChoiceOption(
                    label="No pilot yet",
                    value="no_pilot",
                    description="Install/capture/draft only; data pilot waits for explicit inputs.",
                ),
                ChoiceOption(
                    label="Type something",
                    value="custom",
                    description="Describe the pilot input or strategy.",
                    needs_text=True,
                    text_prompt="Pilot input strategy: ",
                ),
            ),
            default_index=2,
        ),
    )


def choice_option_to_dict(option: ChoiceOption, text: str = "") -> dict[str, str]:
    path = text if option.value == "custom" and text else option.path
    return {
        "choice": option.value,
        "label": option.label,
        "description": option.description,
        "path": path,
        "details": text if option.needs_text else "",
    }


def build_choice_result(program: str, answers: dict[str, dict[str, str]], project_root: Path) -> dict[str, Any]:
    key = program_key(program)
    install = answers["install_location"]
    source = answers["source_type"]
    pilot = answers["pilot_input"]
    source_type = source["choice"]
    project_flag = "" if project_root == Path.cwd().resolve() else f" --project-root {shlex.quote(str(project_root))}"
    suggested_commands: list[str] = [f"python3 scripts/program_onboard.py probe {shlex.quote(program)}{project_flag}"]
    next_steps: list[str] = []

    if install["choice"] == "no_install":
        next_steps.append("Keep the tool at discovery/proposal stage; do not clone, install, or mutate Conda envs.")
    else:
        next_steps.append("Ask for explicit confirmation before network access, clone/build steps, Conda env mutation, or tool-path writes.")
        next_steps.append(f"Use install target: {install.get('path') or install.get('details')}")

    if source_type in {"conda", "github", "container", "binary"}:
        suggested_commands.append(
            f"python3 scripts/program_onboard.py plan-install {shlex.quote(program)} --package {shlex.quote(key)} --source {source_type}{project_flag}"
        )
        if source_type == "conda":
            next_steps.append("Generate a Conda proposal; execute only with install --proposal <json> --yes after review.")
        else:
            next_steps.append("Generate a proposal-only record; manual implementation requires a separate reviewed plan.")
    else:
        next_steps.append("Translate the custom source details into an explicit install proposal before any action.")

    if pilot["choice"] == "no_pilot":
        next_steps.append("After install/discovery, capture help/version and draft the program card before a data pilot.")
    else:
        next_steps.append("Run input preflight on the selected pilot input before generating a script or SLURM job.")

    return {
        "choice_schema_version": "program_onboarding.choice.v1",
        "program": program,
        "program_key": key,
        "project_root": str(project_root),
        "created_at": iso_now(),
        "install_location": install,
        "source_type": source,
        "pilot_input": pilot,
        "suggested_commands": suggested_commands,
        "next_steps": next_steps,
    }


def _to_menu_question(question: ChoiceQuestion) -> tuple["menu.Question", list[ChoiceOption]]:
    """Translate this script's project-specific ChoiceQuestion into a generic
    menu.Question. Returns the menu.Question plus the original ChoiceOption
    list in the same order so the caller can map back after the user picks.
    """
    options = [
        menu.Option(
            label=opt.label,
            description=opt.description,
            value=opt.value,
            needs_text=opt.needs_text,
            text_prompt=opt.text_prompt or "Enter value: ",
        )
        for opt in question.options
    ]
    mq = menu.Question(
        title=question.title,
        options=tuple(options),
        default_index=question.default_index,
    )
    return mq, list(question.options)


def choose_question_with_curses(question: ChoiceQuestion) -> tuple[ChoiceOption, str]:
    """Backward-compatible wrapper. Forces the curses backend; falls back to
    plain only if curses itself errors out inside menu.ask_question.
    """
    mq, originals = _to_menu_question(question)
    chosen, text = menu.ask_question(mq)
    return originals[mq.options.index(chosen)], text


def choose_question_plain(question: ChoiceQuestion) -> tuple[ChoiceOption, str]:
    """Backward-compatible wrapper that always uses the numbered-prompt
    backend regardless of TTY state.
    """
    mq, originals = _to_menu_question(question)
    chosen, text = menu._plain_choose(mq)  # noqa: SLF001
    return originals[mq.options.index(chosen)], text


def collect_choice_answers(
    program: str,
    default_source: str,
    project_root: Path,
    use_plain: bool = False,
) -> dict[str, dict[str, str]]:
    answers: dict[str, dict[str, str]] = {}
    for question in onboarding_choice_questions(program, default_source, project_root):
        if use_plain:
            option, text = choose_question_plain(question)
        else:
            # menu.ask_question already auto-falls-back when TTY is unavailable
            # or curses misbehaves, so we don't need to re-check isatty() here.
            option, text = choose_question_with_curses(question)
        answers[question.key] = choice_option_to_dict(option, text)
    return answers


def default_choice_answers(program: str, default_source: str, project_root: Path) -> dict[str, dict[str, str]]:
    answers: dict[str, dict[str, str]] = {}
    for question in onboarding_choice_questions(program, default_source, project_root):
        option = question.options[question.default_index]
        answers[question.key] = choice_option_to_dict(option)
    return answers


def print_choice_options(program: str, default_source: str, project_root: Path) -> None:
    payload = {
        question.key: [
            {
                "label": option.label,
                "value": option.value,
                "description": option.description,
                "path": option.path,
                "needs_text": option.needs_text,
            }
            for option in question.options
        ]
        for question in onboarding_choice_questions(program, default_source, project_root)
    }
    print(json.dumps(payload, indent=2, ensure_ascii=False))


def choose(args: argparse.Namespace) -> int:
    try:
        project_root = validate_project_root(args.project_root)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    if args.print_options:
        print_choice_options(args.program, args.default_source, project_root)
        return 0

    output = Path(args.output) if args.output else default_choice_output(args.program, project_root)
    try:
        output = validated_choice_output_path(output, project_root, args.allow_external_output)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2

    answers = default_choice_answers(args.program, args.default_source, project_root) if args.defaults else collect_choice_answers(
        args.program,
        args.default_source,
        project_root,
        args.plain,
    )
    result = build_choice_result(args.program, answers, project_root)
    write_text(output, json.dumps(result, indent=2, ensure_ascii=False) + "\n")
    print("Status\tCHOICE_RECORDED")
    print("Program_Key\t" + result["program_key"])
    print("Choice_JSON\t" + rel(output))
    for command in result["suggested_commands"]:
        print("Suggested\t" + command)
    return 0


def run_probe_command(argv: list[str], timeout: int = 8) -> dict[str, Any]:
    try:
        proc = subprocess.run(
            argv,
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        return {
            "argv": argv,
            "exit_code": proc.returncode,
            "stdout": truncate(proc.stdout or ""),
            "stderr": truncate(proc.stderr or ""),
            "timed_out": False,
        }
    except FileNotFoundError as exc:
        return {
            "argv": argv,
            "exit_code": 127,
            "stdout": "",
            "stderr": str(exc),
            "timed_out": False,
        }
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode(errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode(errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return {
            "argv": argv,
            "exit_code": 124,
            "stdout": truncate(stdout),
            "stderr": truncate(stderr),
            "timed_out": True,
        }


def command_output_text(result: dict[str, Any]) -> str:
    pieces = [
        f"$ {shlex.join(result['argv'])}",
        f"exit_code: {result['exit_code']}",
    ]
    if result.get("timed_out"):
        pieces.append("timed_out: true")
    stdout = result.get("stdout") or ""
    stderr = result.get("stderr") or ""
    if stdout:
        pieces.extend(["", "[stdout]", stdout.rstrip()])
    if stderr:
        pieces.extend(["", "[stderr]", stderr.rstrip()])
    return "\n".join(pieces).rstrip() + "\n"


def resolve_executable(program: str, explicit_path: str | None = None) -> tuple[str | None, list[dict[str, str]]]:
    rows: list[dict[str, str]] = []

    if explicit_path:
        path = Path(explicit_path).expanduser()
        status = "FOUND" if path.is_file() and os.access(path, os.X_OK) else "MISSING"
        rows.append(
            {
                "Probe": "explicit_path",
                "Status": status,
                "Value": str(path),
                "Details": "explicit path supplied by user",
            }
        )
        if status == "FOUND":
            return str(path), rows

    if "/" in program:
        path = Path(program).expanduser()
        status = "FOUND" if path.is_file() and os.access(path, os.X_OK) else "MISSING"
        rows.append(
            {
                "Probe": "program_path",
                "Status": status,
                "Value": str(path),
                "Details": "program argument contains a path separator",
            }
        )
        if status == "FOUND":
            return str(path), rows
        return None, rows

    candidates = []
    for candidate in (program, program_key(program), program.lower()):
        if candidate and candidate not in candidates:
            candidates.append(candidate)

    for candidate in candidates:
        found = shutil.which(candidate)
        rows.append(
            {
                "Probe": "command_v",
                "Status": "FOUND" if found else "MISSING",
                "Value": found or "",
                "Details": f"command -v {candidate}",
            }
        )
        if found:
            return found, rows
    return None, rows


def first_successful_flag(executable: str, flags: list[str]) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
    attempts = []
    for flag in flags:
        result = run_probe_command([executable, flag])
        attempts.append(result)
        output = (result.get("stdout") or "") + (result.get("stderr") or "")
        if result["exit_code"] == 0 and output.strip():
            return result, attempts
    return None, attempts


def command_rows(
    executable: str | None,
    write_dir: Path | None = None,
) -> tuple[list[dict[str, str]], dict[str, Any]]:
    rows: list[dict[str, str]] = []
    captures: dict[str, Any] = {"version": None, "help": None}
    if not executable:
        return rows, captures

    version, version_attempts = first_successful_flag(executable, VERSION_FLAGS)
    captures["version"] = version
    version_status = "FOUND" if version else "NO_SUCCESS"
    rows.append(
        {
            "Probe": "version",
            "Status": version_status,
            "Value": shlex.join((version or version_attempts[0])["argv"]) if version_attempts else "",
            "Details": f"{len(version_attempts)} attempt(s)",
        }
    )

    help_result, help_attempts = first_successful_flag(executable, HELP_FLAGS)
    captures["help"] = help_result
    help_status = "FOUND" if help_result else "NO_SUCCESS"
    rows.append(
        {
            "Probe": "help",
            "Status": help_status,
            "Value": shlex.join((help_result or help_attempts[0])["argv"]) if help_attempts else "",
            "Details": f"{len(help_attempts)} attempt(s)",
        }
    )

    if write_dir:
        attempt_rows = []
        for kind, attempts in (("version", version_attempts), ("help", help_attempts)):
            for result in attempts:
                output = (result.get("stdout") or "") + (result.get("stderr") or "")
                attempt_rows.append(
                    {
                        "Kind": kind,
                        "Command": shlex.join(result["argv"]),
                        "Exit_Code": str(result["exit_code"]),
                        "Timed_Out": "yes" if result.get("timed_out") else "no",
                        "Evidence_Usable": "yes" if result["exit_code"] == 0 and output.strip() else "no",
                    }
                )
        write_tsv(
            write_dir / "command_attempts.tsv",
            attempt_rows,
            ["Kind", "Command", "Exit_Code", "Timed_Out", "Evidence_Usable"],
        )
        if version:
            write_text(write_dir / "version.txt", command_output_text(version))
        if help_result:
            write_text(write_dir / "help.txt", command_output_text(help_result))
    return rows, captures


def parse_conda_envs_from_json(text: str) -> list[dict[str, str]]:
    data = json.loads(text)
    envs: list[dict[str, str]] = []
    for prefix in data.get("envs", []):
        path = Path(prefix)
        name = "base" if path == Path(data.get("root_prefix", "")) else path.name
        envs.append({"name": name, "prefix": str(path)})
    return envs


def parse_conda_envs_from_text(text: str) -> list[dict[str, str]]:
    envs: list[dict[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.replace("*", " ").split()
        if len(parts) >= 2 and parts[-1].startswith("/"):
            envs.append({"name": parts[0], "prefix": parts[-1]})
    return envs


def conda_envs() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    rows: list[dict[str, str]] = []
    executable = shutil.which("conda") or shutil.which("mamba")
    if not executable:
        rows.append(
            {
                "Probe": "conda_env_list",
                "Status": "MISSING",
                "Value": "",
                "Details": "neither conda nor mamba was found in PATH",
            }
        )
        return [], rows

    result = run_probe_command([executable, "env", "list", "--json"], timeout=12)
    envs: list[dict[str, str]] = []
    if result["exit_code"] == 0 and result["stdout"].strip():
        try:
            envs = parse_conda_envs_from_json(result["stdout"])
        except json.JSONDecodeError:
            envs = []
    if not envs:
        text_result = run_probe_command([executable, "env", "list"], timeout=12)
        if text_result["exit_code"] == 0:
            envs = parse_conda_envs_from_text(text_result["stdout"])

    status = "FOUND" if envs else "NO_ENVS_OR_PARSE_FAILED"
    rows.append(
        {
            "Probe": "conda_env_list",
            "Status": status,
            "Value": executable,
            "Details": f"{len(envs)} environment(s) parsed",
        }
    )
    for env in envs:
        rows.append(
            {
                "Probe": "conda_env",
                "Status": "FOUND",
                "Value": env["name"],
                "Details": env["prefix"],
            }
        )
    return envs, rows


def find_env(env_name: str) -> dict[str, str] | None:
    envs, _rows = conda_envs()
    for env in envs:
        if env["name"] == env_name:
            return env
    return None


def environment_proof(
    program: str,
    executable: str | None,
    captures: dict[str, Any],
    envs: list[dict[str, str]],
) -> str:
    lines = [
        "# Environment proof",
        "",
        f"- Program: `{program}`",
        f"- Captured at: `{iso_now()}`",
        f"- Executable: `{executable or 'not found'}`",
        f"- CONDA_DEFAULT_ENV: `{os.environ.get('CONDA_DEFAULT_ENV', '')}`",
        f"- CONDA_PREFIX: `{os.environ.get('CONDA_PREFIX', '')}`",
    ]
    if executable:
        matched = [
            env
            for env in envs
            if env.get("prefix") and str(Path(executable).resolve()).startswith(str(Path(env["prefix"]).resolve()))
        ]
        if matched:
            lines.append(f"- Matching Conda env: `{matched[0]['name']}` (`{matched[0]['prefix']}`)")
    for label in ("version", "help"):
        result = captures.get(label)
        if result:
            lines.append(f"- {label} command: `{shlex.join(result['argv'])}`")
            lines.append(f"- {label} exit code: `{result['exit_code']}`")
    startup = captures.get("version") or captures.get("help")
    if startup:
        ok = startup["exit_code"] == 0 and bool((startup.get("stdout") or startup.get("stderr") or "").strip())
        lines.append(f"- Startup check: `{'PASS' if ok else 'CHECK_FAILED'}`")
    else:
        lines.append("- Startup check: `NOT_RUN`")
    return "\n".join(lines) + "\n"


def collect_local_discovery(program: str, explicit_path: str | None, bundle: Path) -> tuple[str | None, list[dict[str, str]], dict[str, Any], list[dict[str, str]]]:
    executable, rows = resolve_executable(program, explicit_path)
    command_probe_rows, captures = command_rows(executable, bundle)
    rows.extend(command_probe_rows)
    envs, env_rows = conda_envs()
    rows.extend(env_rows)
    write_tsv(bundle / "local_discovery.tsv", rows, ["Probe", "Status", "Value", "Details"])
    write_text(bundle / "environment_proof.md", environment_proof(program, executable, captures, envs))
    return executable, rows, captures, envs


def probe(args: argparse.Namespace) -> int:
    key = program_key(args.program)
    try:
        project_root = validate_project_root(args.project_root)
        out_root = validated_out_root(args.out_root, project_root, args.allow_external_paths)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    bundle = ensure_bundle(key, out_root)
    executable, _rows, _captures, _envs = collect_local_discovery(args.program, args.path, bundle)
    status = "INSTALLED" if executable else "UNKNOWN"
    write_intent(bundle, args.program, key, "probe", status)

    print("Status\t" + status)
    print("Program_Key\t" + key)
    print("Evidence_Dir\t" + rel(bundle))
    if executable:
        print("Executable\t" + executable)
        print("Next\tpython3 scripts/program_onboard.py capture " + shlex.quote(args.program) + " --evidence-dir " + shlex.quote(str(bundle)))
    else:
        print("Next\tpython3 scripts/program_onboard.py plan-install " + shlex.quote(args.program) + " --package " + shlex.quote(key) + " --source conda")
    return 0


def package_spec(package: str, version_spec: str) -> str:
    spec = version_spec.strip()
    if not spec:
        return package
    if spec.startswith(("=", ">", "<", "!")):
        return package + spec
    return f"{package}={spec}"


def validate_package_name(package: str) -> bool:
    return not unsafe_token(package)


def validate_version_spec(version_spec: str) -> bool:
    if not version_spec:
        return True
    return not unsafe_token(version_spec.lstrip("=<>!~"))


def validate_channel_name(channel: str) -> bool:
    return not unsafe_token(channel)


def channel_args(channels: list[str]) -> list[str]:
    argv: list[str] = []
    for channel in channels:
        argv.extend(["-c", channel])
    return argv


def installer_name() -> str:
    if shutil.which("mamba"):
        return "mamba"
    if shutil.which("conda"):
        return "conda"
    return "mamba"


def build_conda_argv_with_installer(
    installer: str,
    target_env: str,
    package_name: str,
    version_spec: str,
    channels: list[str],
    reuse_existing: bool,
) -> list[str]:
    action = "install" if reuse_existing else "create"
    return [
        installer,
        action,
        "-y",
        "-n",
        target_env,
        *channel_args(channels),
        package_spec(package_name, version_spec),
    ]


def build_conda_argv(
    target_env: str,
    package_name: str,
    version_spec: str,
    channels: list[str],
    reuse_existing: bool,
) -> list[str]:
    return build_conda_argv_with_installer(
        installer_name(),
        target_env,
        package_name,
        version_spec,
        channels,
        reuse_existing,
    )


def proposal_markdown(proposal: dict[str, Any]) -> str:
    commands = proposal_command_strings(proposal)
    risk_notes = proposal.get("risk_notes") or []
    expected_writes = proposal.get("expected_writes") or []
    lines = [
        "# Install proposal",
        "",
        f"- Program key: `{proposal['program_key']}`",
        f"- Package name: `{proposal['package_name']}`",
        f"- Version spec: `{proposal['version_spec'] or 'latest available'}`",
        f"- Source type: `{proposal['source_type']}`",
        f"- Install method: `{proposal['install_method']}`",
        f"- Target env: `{proposal['target_env']}`",
        f"- Network required: `{proposal['network_required']}`",
        f"- Created at: `{proposal['created_at']}`",
        "",
        "## Channels",
        "",
    ]
    for channel in proposal.get("channels") or []:
        lines.append(f"- `{channel}`")
    lines.extend(["", "## Commands", ""])
    if commands:
        lines.append("```bash")
        lines.extend(commands)
        lines.append("```")
    else:
        lines.append("No automatic install command is supported for this source type.")
    lines.extend(["", "## Expected writes", ""])
    for item in expected_writes:
        lines.append(f"- {item}")
    lines.extend(["", "## Risk notes", ""])
    for item in risk_notes:
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "## Confirmation gate",
            "",
            "Run only after review:",
            "",
            "```bash",
            f"python3 scripts/program_onboard.py install --proposal {rel(Path(proposal['evidence_dir']) / 'install_proposal.json')} --yes",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def plan_install(args: argparse.Namespace) -> int:
    key = program_key(args.program)
    package_name = args.package or key
    target_env = args.target_env or f"bio_{key}"
    source_type = args.source
    channels = args.channel or DEFAULT_CHANNELS
    try:
        project_root = validate_project_root(args.project_root)
        out_root = validated_out_root(args.out_root, project_root)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    bundle = ensure_bundle(key, out_root)

    discovery_rows: list[dict[str, str]] = []
    envs, env_rows = conda_envs()
    discovery_rows.extend(env_rows)
    write_tsv(bundle / "local_discovery.tsv", discovery_rows, ["Probe", "Status", "Value", "Details"])

    if source_type == "conda" and not safe_env_name(target_env):
        write_intent(bundle, args.program, key, "plan-install", "BLOCKED", {"Reason": "unsafe target env name"})
        print("Status\tBLOCKED")
        print("Reason\tTarget env must be a simple Conda env name, not a path")
        print("Evidence_Dir\t" + rel(bundle))
        return 1
    if source_type == "conda" and not validate_package_name(package_name):
        write_intent(bundle, args.program, key, "plan-install", "BLOCKED", {"Reason": "unsafe package name"})
        print("Status\tBLOCKED")
        print("Reason\tPackage name must be a simple Conda package token")
        print("Evidence_Dir\t" + rel(bundle))
        return 1
    if source_type == "conda" and not validate_version_spec(args.version or ""):
        write_intent(bundle, args.program, key, "plan-install", "BLOCKED", {"Reason": "unsafe version spec"})
        print("Status\tBLOCKED")
        print("Reason\tVersion spec contains unsafe characters")
        print("Evidence_Dir\t" + rel(bundle))
        return 1
    bad_channels = [channel for channel in channels if not validate_channel_name(channel)]
    if source_type == "conda" and bad_channels:
        write_intent(bundle, args.program, key, "plan-install", "BLOCKED", {"Reason": "unsafe channel"})
        print("Status\tBLOCKED")
        print("Reason\tConda channels must be simple channel tokens: " + ", ".join(bad_channels))
        print("Evidence_Dir\t" + rel(bundle))
        return 1

    existing_env = next((env for env in envs if env["name"] == target_env), None)
    if source_type == "conda" and existing_env and not args.reuse_existing:
        write_intent(bundle, args.program, key, "plan-install", "BLOCKED", {"Reason": "target env exists"})
        print("Status\tBLOCKED")
        print("Reason\tTarget env already exists: " + target_env)
        print("Existing_Env_Prefix\t" + existing_env["prefix"])
        print("Use\t--reuse-existing to explicitly plan installation into that env")
        print("Evidence_Dir\t" + rel(bundle))
        return 1

    if source_type == "conda":
        argv = build_conda_argv(target_env, package_name, args.version or "", channels, args.reuse_existing)
        install_method = "conda_install_existing_env" if args.reuse_existing else "conda_create_env"
        commands = [shlex.join(argv)]
        command_argv = [argv]
        expected_writes = [
            f"Conda environment named {target_env}",
            "Conda/Mamba package cache in the user's configured Conda directories",
        ]
        risk_notes = [
            "Requires network access unless packages are already cached.",
            "Mutates a Conda environment; rollback may require removing or repairing the env.",
            "If the env appears before execution and reuse_existing is false, install will block.",
        ]
        network_required = True
    else:
        install_method = f"{source_type}_proposal_only"
        commands = []
        command_argv = []
        expected_writes = ["No automatic writes are defined by third-version onboarding."]
        risk_notes = [
            "This source type is proposal-only in program_onboard.py.",
            "Review official installation instructions and confirm target paths before any manual action.",
            "Do not write under ~/tools/ without separate confirmation.",
        ]
        network_required = source_type in {"container", "github", "source", "binary"}

    proposal = {
        "proposal_schema_version": SCHEMA_VERSION,
        "created_by": CREATED_BY,
        "program_key": key,
        "program_name": args.program,
        "package_name": package_name,
        "version_spec": args.version or "",
        "source_type": source_type,
        "install_method": install_method,
        "target_env": target_env,
        "channels": channels,
        "commands": commands,
        "command_argv": command_argv,
        "expected_writes": expected_writes,
        "network_required": network_required,
        "risk_notes": risk_notes,
        "reuse_existing": bool(args.reuse_existing),
        "created_at": iso_now(),
        "evidence_dir": str(bundle),
    }
    write_text(bundle / "install_proposal.json", json.dumps(proposal, indent=2, ensure_ascii=False) + "\n")
    write_text(bundle / "install_proposal.md", proposal_markdown(proposal))
    write_intent(bundle, args.program, key, "plan-install", "PROPOSED")

    print("Status\tPROPOSED")
    print("Program_Key\t" + key)
    print("Target_Env\t" + target_env)
    print("Proposal_JSON\t" + rel(bundle / "install_proposal.json"))
    print("Proposal_MD\t" + rel(bundle / "install_proposal.md"))
    if commands:
        print("Command\t" + commands[0])
    else:
        print("Command\tPROPOSAL_ONLY")
    return 0


REQUIRED_PROPOSAL_FIELDS = {
    "proposal_schema_version",
    "created_by",
    "program_key",
    "program_name",
    "package_name",
    "version_spec",
    "source_type",
    "install_method",
    "target_env",
    "channels",
    "commands",
    "command_argv",
    "expected_writes",
    "network_required",
    "risk_notes",
    "reuse_existing",
    "created_at",
    "evidence_dir",
}


def load_proposal(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_PROPOSAL_FIELDS - set(data))
    if missing:
        raise ValueError("proposal missing required field(s): " + ", ".join(missing))
    if data.get("created_by") != CREATED_BY or data.get("proposal_schema_version") != SCHEMA_VERSION:
        raise ValueError("proposal was not generated by this version of program_onboard.py")
    return data


def resolve_install_proposal_path(path: Path) -> Path:
    resolved = path.expanduser().resolve()
    if is_protected_write_path(resolved):
        raise ValueError("proposal path must not be under a protected data/tools directory (e.g. ~/data or ~/tools)")
    if resolved.name != "install_proposal.json":
        raise ValueError("proposal path must be named install_proposal.json")
    validate_bundle_dir(resolved.parent)
    return resolved


def validate_conda_proposal(proposal: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if proposal.get("source_type") != "conda":
        errors.append("automatic install only supports source_type=conda")
    if proposal.get("install_method") not in {"conda_create_env", "conda_install_existing_env"}:
        errors.append("install_method is not a supported Conda method")
    target_env = str(proposal.get("target_env", ""))
    if not safe_env_name(target_env):
        errors.append("target_env must be a simple Conda env name, not a path")

    package_name = str(proposal.get("package_name", ""))
    if not validate_package_name(package_name):
        errors.append("package_name must be a simple Conda package token")

    version_spec = str(proposal.get("version_spec", ""))
    if not validate_version_spec(version_spec):
        errors.append("version_spec contains unsafe characters")

    channels = proposal.get("channels")
    if not isinstance(channels, list) or not channels or not all(isinstance(channel, str) for channel in channels):
        errors.append("channels must be a non-empty list of strings")
        channels = []
    else:
        bad_channels = [channel for channel in channels if not validate_channel_name(channel)]
        if bad_channels:
            errors.append("channels contain unsafe token(s): " + ", ".join(bad_channels))

    command_argv = proposal.get("command_argv")
    if not isinstance(command_argv, list) or len(command_argv) != 1 or not isinstance(command_argv[0], list):
        errors.append("proposal must contain exactly one command_argv list")
        return errors

    argv = [str(part) for part in command_argv[0]]
    if not argv or Path(argv[0]).name not in {"mamba", "conda"}:
        errors.append("installer must be mamba or conda")
        installer = ""
    else:
        installer = Path(argv[0]).name
    expected_action = "install" if proposal.get("reuse_existing") else "create"
    if len(argv) < 6 or argv[1] != expected_action:
        errors.append(f"Conda command must use '{expected_action}'")
    if "-n" not in argv:
        errors.append("Conda command must name the target env with -n")
    else:
        env_arg = argv[argv.index("-n") + 1] if argv.index("-n") + 1 < len(argv) else ""
        if env_arg != target_env:
            errors.append("Conda command target env does not match proposal target_env")
    user_tools_prefix = str(Path.home() / "tools")
    if any(user_tools_prefix in part for part in argv):
        errors.append("automatic install command must not write under ~/tools/")
    if any(part in {";", "&&", "||", "|", ">", ">>"} for part in argv):
        errors.append("command_argv contains shell control syntax")

    if installer and not errors:
        expected_argv = build_conda_argv_with_installer(
            installer,
            target_env,
            package_name,
            version_spec,
            channels,
            bool(proposal.get("reuse_existing")),
        )
        if argv != expected_argv:
            errors.append("command_argv does not exactly match proposal fields")
        expected_commands = [shlex.join(expected_argv)]
        if proposal.get("commands") != expected_commands:
            errors.append("commands does not exactly match command_argv")
    return errors


def proposal_summary(proposal: dict[str, Any]) -> str:
    commands = proposal_command_strings(proposal)
    lines = [
        "Install summary:",
        f"- Program key: {proposal['program_key']}",
        f"- Target env: {proposal['target_env']}",
        f"- Source type: {proposal['source_type']}",
        f"- Network required: {proposal['network_required']}",
        "- Expected writes:",
    ]
    for item in proposal.get("expected_writes") or []:
        lines.append(f"  - {item}")
    lines.append("- Command:")
    lines.extend(f"  {command}" for command in commands)
    return "\n".join(lines)


def proposal_command_strings(proposal: dict[str, Any]) -> list[str]:
    command_argv = proposal.get("command_argv")
    if isinstance(command_argv, list) and len(command_argv) == 1 and isinstance(command_argv[0], list):
        return [shlex.join([str(part) for part in command_argv[0]])]
    return [str(command) for command in (proposal.get("commands") or [])]


def install(args: argparse.Namespace) -> int:
    try:
        proposal_path = resolve_install_proposal_path(Path(args.proposal))
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    try:
        proposal = load_proposal(proposal_path)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print("Status\tERROR")
        print("Reason\t" + str(exc))
        return 2

    proposal_evidence_dir = Path(str(proposal.get("evidence_dir", ""))).resolve()
    if proposal_evidence_dir != proposal_path.parent.resolve():
        print("Status\tBLOCKED")
        print("Reason\tproposal evidence_dir must match the proposal directory")
        return 2

    print(proposal_summary(proposal))
    if not args.yes:
        print("Status\tBLOCKED")
        print("Reason\tinstall requires --yes after reviewing the proposal")
        return 2

    errors = validate_conda_proposal(proposal)
    if errors:
        print("Status\tBLOCKED")
        for error in errors:
            print("Reason\t" + error)
        return 2

    target_env = proposal["target_env"]
    env_exists = find_env(target_env)
    if proposal.get("reuse_existing"):
        if not env_exists:
            print("Status\tBLOCKED")
            print("Reason\treuse_existing is true but target env is not present: " + target_env)
            return 2
    elif env_exists:
        print("Status\tBLOCKED")
        print("Reason\tTarget env already exists: " + target_env)
        print("Existing_Env_Prefix\t" + env_exists["prefix"])
        return 2

    argv = [str(part) for part in proposal["command_argv"][0]]
    installer = shutil.which(argv[0])
    if not installer:
        print("Status\tBLOCKED")
        print("Reason\tInstaller not found in PATH: " + argv[0])
        return 2
    argv[0] = installer

    log_path = proposal_path.parent / "install.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        log.write("# install.log\n")
        log.write("created_at\t" + iso_now() + "\n")
        log.write("command\t" + shlex.join(argv) + "\n\n")
        log.flush()
        proc = subprocess.run(argv, stdout=log, stderr=subprocess.STDOUT, text=True, check=False)
        log.write("\nexit_code\t" + str(proc.returncode) + "\n")

    print("Install_Log\t" + rel(log_path))
    if proc.returncode != 0:
        print("Status\tFAILED")
        print("Exit_Code\t" + str(proc.returncode))
        return proc.returncode
    print("Status\tINSTALLED")
    print("Next\tpython3 scripts/program_onboard.py capture " + shlex.quote(proposal["program_name"]) + " --evidence-dir " + shlex.quote(str(proposal_path.parent)))
    return 0


def capture(args: argparse.Namespace) -> int:
    key = program_key(args.program)
    try:
        project_root = validate_project_root(args.project_root)
        if args.evidence_dir:
            bundle = validate_bundle_dir(resolve_under_project(args.evidence_dir, project_root), project_root, args.allow_external_paths)
        else:
            out_root = validated_out_root(args.out_root, project_root, args.allow_external_paths)
            bundle = ensure_bundle(key, out_root)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    bundle.mkdir(parents=True, exist_ok=True)
    executable, _rows, _captures, _envs = collect_local_discovery(args.program, args.path, bundle)
    status = "CAPTURED" if executable else "MISSING"
    write_intent(bundle, args.program, key, "capture", status)
    print("Status\t" + status)
    print("Program_Key\t" + key)
    print("Evidence_Dir\t" + rel(bundle))
    if executable:
        print("Executable\t" + executable)
    print("Next\tpython3 scripts/program_onboard.py draft-card " + shlex.quote(str(bundle)))
    return 0 if executable else 1


def load_proposal_if_present(bundle: Path) -> dict[str, Any]:
    path = bundle / "install_proposal.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def evidence_grade(bundle: Path) -> str:
    for filename in ("help.txt", "version.txt"):
        path = bundle / filename
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if "exit_code: 0" in text and text.strip():
            return "local_help"
    return "inferred"


def short_output_summary(path: Path) -> str:
    if not path.exists():
        return "not captured"
    text = path.read_text(encoding="utf-8").strip().splitlines()
    for line in text:
        stripped = line.strip()
        if (
            stripped
            and not stripped.startswith("$")
            and not stripped.startswith("exit_code:")
            and stripped not in {"[stdout]", "[stderr]"}
        ):
            return stripped[:160]
    return "captured; inspect evidence bundle"


def draft_card_text(bundle: Path, output_path: Path) -> str:
    intent = read_intent(bundle)
    proposal = load_proposal_if_present(bundle)
    key = proposal.get("program_key") or intent.get("Program_Key") or bundle.parent.name
    display = intent.get("Program") or proposal.get("program_name") or key
    package_name = proposal.get("package_name") or key
    target_env = proposal.get("target_env") or f"bio_{key}"
    source_type = proposal.get("source_type") or "unknown"
    grade = evidence_grade(bundle)
    rel_bundle = rel(bundle)
    rel_output = rel(output_path)

    lines = [
        f"# {display} program card draft",
        "",
        "Draft status: not registered. Review this card after a real pilot run before",
        "moving it to the active program-card directory and adding it to `registry.tsv`.",
        "",
        f"- Program key: `{key}`",
        f"- Evidence bundle: `{rel_bundle}`",
        f"- Draft path: `{rel_output}`",
        f"- Proposed package: `{package_name}`",
        f"- Proposed source: `{source_type}`",
        f"- Proposed env: `{target_env}`",
        f"- Version evidence: {short_output_summary(bundle / 'version.txt')}",
        f"- Help evidence: {short_output_summary(bundle / 'help.txt')}",
        "",
        "## Supported modes",
        "",
        "- `unknown`: replace with a concrete mode after confirming the biological goal, input contract, and output type.",
        "",
        "## Environment preflight",
        "",
        f"- Check `command -v {display}` or the package-specific executable name before running.",
        f"- Proposed Conda env: `{target_env}`.",
        f"- Installation evidence, if any, is in `{rel_bundle}`.",
        "- Do not install, update, or reuse an existing env without user confirmation.",
        "",
        "## Required inputs by mode",
        "",
        "- `unknown`: define required files, indexes, manifests, and compatibility constraints before generating a run script.",
        "",
        "## Input preparation",
        "",
        "- Require explicit input paths, a manifest, or a user-approved bounded search root plus pattern and maxdepth.",
        "- Record naming, coordinate, compression, and overwrite constraints before execution.",
        "",
        "## Parameter negotiation",
        "",
        "- Must ask: parameters that alter biological interpretation, output schema, resource use, or rerun behavior.",
        "- Can infer: only values proven by local help or unambiguous file metadata.",
        "- Must record: defaults that affect reproducibility.",
        "",
        "## Resource model",
        "",
        "- Link to `../software-resource-cards.md` for shared resource guidance.",
        "- Treat memory, disk, thread scaling, and runtime as unknown until a pilot run exists.",
        "- Start with a small pilot before scaling to a full sample set or genome-wide run.",
        "",
        "## Script generation notes",
        "",
        "- Use strict shell mode, explicit output directories, project-local temp paths, and version logging.",
        "- Activate the target env or use absolute binary paths; record `which`, version, and help evidence in logs.",
        "- Add overwrite guards for every expected output.",
        "",
        "## Acceptance checks",
        "",
        "- Verify required outputs exist and are non-empty.",
        "- Parse any summary metrics or logs that prove the selected mode completed.",
        "- Check format, coordinate, ID, and sample-count consistency against the inputs.",
        "- Upgrade evidence only after a pilot or real run succeeds.",
        "",
        "## Common failures and recovery",
        "",
        "- Failure symptom: missing executable or env activation failure. Minimal recovery: rerun capture and inspect `environment_proof.md`.",
        "- Failure symptom: unsupported input or parameter. Minimal recovery: inspect local help and run a one-sample pilot.",
        "- Failure symptom: empty or malformed output. Minimal recovery: keep logs, validate inputs, and rerun only after the cause is identified.",
        "",
        "## Evidence grade",
        "",
        f"- `{grade}`: generated from local onboarding evidence in `{rel_bundle}`.",
        "- `inferred`: all mode, input, parameter, and resource claims still need review unless explicitly proven above.",
        "- Do not write run-proven evidence grades until a real pilot or production run has completed successfully.",
        "",
    ]
    return "\n".join(lines)


def draft_card(args: argparse.Namespace) -> int:
    try:
        project_root = validate_project_root(args.project_root)
        bundle = validate_bundle_dir(resolve_under_project(args.evidence_dir, project_root), project_root, args.allow_external_paths)
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    if not bundle.exists() or not bundle.is_dir():
        print("Status\tERROR")
        print("Reason\tEvidence dir not found: " + str(bundle))
        return 2
    intent = read_intent(bundle)
    proposal = load_proposal_if_present(bundle)
    key = proposal.get("program_key") or intent.get("Program_Key") or bundle.parent.name
    try:
        output_path = validated_draft_path(
            Path(args.output_card) if args.output_card else CARD_DRAFT_DIR / f"{key}.md",
            args.allow_external_paths,
        )
    except ValueError as exc:
        print("Status\tBLOCKED")
        print("Reason\t" + str(exc))
        return 2
    existed = output_path.exists()
    if existed and not args.force:
        print("Status\tBLOCKED")
        print("Reason\tDraft card already exists; use --force to overwrite")
        print("Draft_Card\t" + rel(output_path))
        return 2
    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = draft_card_text(bundle, output_path)
    write_text(output_path, text)
    write_text(bundle / "card_draft.md", text)
    print("Status\t" + ("OVERWRITTEN" if existed else "DRAFTED"))
    print("Draft_Card\t" + rel(output_path))
    print("Evidence_Copy\t" + rel(bundle / "card_draft.md"))
    print("Next\tReview manually, run a pilot, then move to active cards and update registry.tsv only after confirmation")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Choose options, probe, plan, install, capture, and draft cards for unknown programs."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    choose_parser = subparsers.add_parser("choose", help="Record interactive onboarding choices without installing")
    choose_parser.add_argument("program", help="Program name")
    choose_parser.add_argument("--output", help="Output JSON path; defaults to config/program-onboarding/<program_key>_choice.json")
    choose_parser.add_argument("--project-root", help="Project root for choice output; defaults to current directory")
    choose_parser.add_argument("--plain", action="store_true", help="Use numbered prompts instead of curses")
    choose_parser.add_argument("--print-options", action="store_true", help="Print available choices and exit")
    choose_parser.add_argument("--defaults", action="store_true", help="Write recommended defaults without prompting")
    choose_parser.add_argument(
        "--default-source",
        default="conda",
        choices=["conda", "github", "container", "binary", "custom"],
        help="Default source choice to highlight; use github for source-only tools.",
    )
    choose_parser.add_argument(
        "--allow-external-output",
        action="store_true",
        help="Allow project-external output path for smoke tests.",
    )
    choose_parser.set_defaults(func=choose)

    probe_parser = subparsers.add_parser("probe", help="Run cheap local discovery without installing")
    probe_parser.add_argument("program", help="Program name or explicit executable path")
    probe_parser.add_argument("--path", help="Explicit executable path to check before PATH lookup")
    probe_parser.add_argument("--out-root", help="Evidence root; defaults to reports/program-onboarding")
    probe_parser.add_argument("--project-root", help="Project root for evidence output; defaults to current directory")
    probe_parser.add_argument(
        "--allow-external-paths",
        action="store_true",
        help="Allow project-external evidence paths for smoke tests; never used by install.",
    )
    probe_parser.set_defaults(func=probe)

    plan_parser = subparsers.add_parser("plan-install", help="Write an install proposal without executing it")
    plan_parser.add_argument("program", help="Program name")
    plan_parser.add_argument("--package", help="Conda/package name; defaults to normalized program key")
    plan_parser.add_argument("--version", default="", help="Optional package version constraint")
    plan_parser.add_argument(
        "--source",
        default="conda",
        choices=["conda", "container", "github", "source", "binary"],
        help="Install source type. Only conda can be executed by this tool.",
    )
    plan_parser.add_argument("--target-env", help="Target Conda env name; defaults to bio_<program_key>")
    plan_parser.add_argument(
        "--channel",
        action="append",
        help="Conda channel. Repeat to override defaults; default is conda-forge, bioconda, defaults.",
    )
    plan_parser.add_argument(
        "--reuse-existing",
        action="store_true",
        help="Explicitly allow proposal to install into an existing target env.",
    )
    plan_parser.add_argument("--out-root", help="Evidence root; defaults to reports/program-onboarding")
    plan_parser.add_argument("--project-root", help="Project root for evidence output; defaults to current directory")
    plan_parser.set_defaults(func=plan_install)

    install_parser = subparsers.add_parser("install", help="Execute a generated Conda install proposal")
    install_parser.add_argument("--proposal", required=True, help="Path to install_proposal.json")
    install_parser.add_argument("--yes", action="store_true", help="Required confirmation to execute")
    install_parser.set_defaults(func=install)

    capture_parser = subparsers.add_parser("capture", help="Capture which/version/help evidence after install")
    capture_parser.add_argument("program", help="Program name or executable path")
    capture_parser.add_argument("--path", help="Explicit executable path to check before PATH lookup")
    capture_parser.add_argument("--evidence-dir", help="Existing evidence bundle to update")
    capture_parser.add_argument("--out-root", help="Evidence root for a new bundle")
    capture_parser.add_argument("--project-root", help="Project root for evidence output; defaults to current directory")
    capture_parser.add_argument(
        "--allow-external-paths",
        action="store_true",
        help="Allow project-external evidence paths for smoke tests; never used by install.",
    )
    capture_parser.set_defaults(func=capture)

    draft_parser = subparsers.add_parser("draft-card", help="Generate a program card draft from evidence")
    draft_parser.add_argument("evidence_dir", help="Evidence bundle directory")
    draft_parser.add_argument("--output-card", help="Draft card path; defaults to references/program-cards/drafts/<program_key>.md")
    draft_parser.add_argument("--project-root", help="Project root for resolving the evidence dir; defaults to current directory")
    draft_parser.add_argument("--force", action="store_true", help="Overwrite an existing draft card")
    draft_parser.add_argument(
        "--allow-external-paths",
        action="store_true",
        help="Allow project-external evidence and draft paths for smoke tests; never used by install.",
    )
    draft_parser.set_defaults(func=draft_card)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
